/* Generated by JSIL v0.8.2 build 30762. See http://jsil.org/ for more information. */ 
'use strict';
var $asm07 = JSIL.DeclareAssembly("SampleCalculatorApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.DeclareNamespace("SampleCalculatorApp1");
/* class SampleCalculatorApp1.App */ 

(function App$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm00.Windows.UI.Xaml.Application)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm07.SampleCalculatorApp1.MainPage)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm00.Windows.UI.Xaml.Window)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm00.Windows.UI.Xaml.ResourceDictionary)) ();
  };

  function App__ctor () {
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    var mainPage = new ($T01())();
    $T02().Window$Current$value['set_Content'](mainPage);
  };

  function App_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      var ResourceDictionary_7f5137151267447b981d68269579895d = new ($T03())();
      this.Application$Resources$value = ResourceDictionary_7f5137151267447b981d68269579895d;
    }
  };

  JSIL.MakeType({
      BaseType: $asm00.TypeRef("Windows.UI.Xaml.Application"), 
      Name: "SampleCalculatorApp1.App", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      App__ctor
    );

    $.Method({Static:false, Public:false}, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      App_InitializeComponent
    );

    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SampleCalculatorApp1.MainPage */ 

(function MainPage$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Page)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.TextBlock)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm07.SampleCalculatorApp1.PaperTrail)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm06.System.Char)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm06.System.String)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm06.System.Int32)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm07.SampleCalculatorApp1.MainPage_Operation)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm06.System.Exception)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm06.System.Double)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm06.System.Convert)) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm06.System.Math)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm06.System.Object)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm00.Windows.UI.Xaml.RoutedEventArgs)) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.ContentControl)) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Button)) ();
  };
  var $T0F = function () {
    return ($T0F = JSIL.Memoize(System.Array.Of($asm06.System.Char))) ();
  };
  var $T10 = function () {
    return ($T10 = JSIL.Memoize($asm00.Windows.UI.Xaml.Style)) ();
  };
  var $T11 = function () {
    return ($T11 = JSIL.Memoize($asm00.Windows.UI.Xaml.Setter)) ();
  };
  var $T12 = function () {
    return ($T12 = JSIL.Memoize($asm00.Windows.UI.Xaml.FrameworkElement)) ();
  };
  var $T13 = function () {
    return ($T13 = JSIL.Memoize($asm00.DotNetForHtml5.Core.TypeFromStringConverters)) ();
  };
  var $T14 = function () {
    return ($T14 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Control)) ();
  };
  var $T15 = function () {
    return ($T15 = JSIL.Memoize($asm00.Windows.UI.Xaml.Media.Brush)) ();
  };
  var $T16 = function () {
    return ($T16 = JSIL.Memoize($asm06.System.Collections.ObjectModel.Collection$b1.Of($asm00.Windows.UI.Xaml.Setter))) ();
  };
  var $T17 = function () {
    return ($T17 = JSIL.Memoize($asm00.Windows.UI.Xaml.ResourceDictionary)) ();
  };
  var $T18 = function () {
    return ($T18 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.ScrollViewer)) ();
  };
  var $T19 = function () {
    return ($T19 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.ScrollBarVisibility)) ();
  };
  var $T1A = function () {
    return ($T1A = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Canvas)) ();
  };
  var $T1B = function () {
    return ($T1B = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Panel)) ();
  };
  var $T1C = function () {
    return ($T1C = JSIL.Memoize($asm00.Windows.UI.Xaml.HorizontalAlignment)) ();
  };
  var $T1D = function () {
    return ($T1D = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Border)) ();
  };
  var $T1E = function () {
    return ($T1E = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.UserControl)) ();
  };
  var $T1F = function () {
    return ($T1F = JSIL.Memoize($asm00.Windows.UI.Xaml.Thickness)) ();
  };
  var $T20 = function () {
    return ($T20 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Primitives.ButtonBase)) ();
  };
  var $T21 = function () {
    return ($T21 = JSIL.Memoize($asm00.Windows.UI.Xaml.RoutedEventHandler)) ();
  };
  var $T22 = function () {
    return ($T22 = JSIL.Memoize($asm00.System.Windows.Markup.StaticResource)) ();
  };
  var $T23 = function () {
    return ($T23 = JSIL.Memoize($asm06.System.Collections.ObjectModel.Collection$b1.Of($asm00.Windows.UI.Xaml.UIElement))) ();
  };
  var $T24 = function () {
    return ($T24 = JSIL.Memoize($asm06.System.Collections.Generic.List$b1.Of($asm06.System.Object))) ();
  };
  var $T25 = function () {
    return ($T25 = JSIL.Memoize($asm03.System.Windows.Markup.MarkupExtension)) ();
  };
  var $T26 = function () {
    return ($T26 = JSIL.Memoize($asm00.System.ServiceProvider)) ();
  };
  var $T27 = function () {
    return ($T27 = JSIL.Memoize($asm06.System.Boolean)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm07.TypeRef("SampleCalculatorApp1.PaperTrail"), [$asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")]))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(new JSIL.MethodSignature($asm06.TypeRef("System.Double"), [$asm06.TypeRef("System.String")]))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(new JSIL.ConstructorSignature($asm06.TypeRef("System.Exception"), [$asm06.TypeRef("System.String")]))) ();
  };
  var $S03 = function () {
    return ($S03 = JSIL.Memoize(new JSIL.ConstructorSignature($asm00.TypeRef("Windows.UI.Xaml.Style"), null))) ();
  };
  var $S04 = function () {
    return ($S04 = JSIL.Memoize(new JSIL.ConstructorSignature($asm00.TypeRef("Windows.UI.Xaml.Setter"), null))) ();
  };
  var $S05 = function () {
    return ($S05 = JSIL.Memoize(new JSIL.ConstructorSignature($asm00.TypeRef("System.Windows.Markup.StaticResource"), null))) ();
  };
  var $S06 = function () {
    return ($S06 = JSIL.Memoize(new JSIL.ConstructorSignature($asm06.TypeRef("System.Collections.Generic.List`1", [$asm06.TypeRef("System.Object")]), null))) ();
  };

  function MainPage__ctor () {
    this._display = "";
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    this.PaperBox = new ($T01())();
    this.Paper = $S00().Construct(this.PaperBox);
    this['ProcessKey']("0");
    this['set_EraseDisplay'](true);
  };

  function MainPage_AddToDisplay (c) {
    if ((c['charCodeAt'](0) | 0) === ((".")['charCodeAt'](0) | 0)) {
      if ((this['get_Display']().indexOf(".", 0)) >= 0) {
        return;
      }
      this['set_Display'](JSIL.ConcatString(this['get_Display'](), c));
    } else if (!(((c['charCodeAt'](0) | 0) < (("0")['charCodeAt'](0) | 0)) || ((c['charCodeAt'](0) | 0) > (("9")['charCodeAt'](0) | 0)))) {
      this['set_Display'](JSIL.ConcatString(this['get_Display'](), c));
    } else if ((c['charCodeAt'](0) | 0) === (("\x08")['charCodeAt'](0) | 0)) {
      if ((this['get_Display']().length | 0) <= 1) {
        this['set_Display']($T04().Empty);
      } else {
        var i = (this['get_Display']().length | 0);
        this['set_Display'](System.String.Remove(this['get_Display'](), ((i - 1) | 0), 1));
      }
    }
    this['UpdateDisplay']();
  };

  function MainPage_Calc (LastOper, $exception) {
    var d = 0;
    try {
      switch (LastOper['valueOf']()) {
        case 1: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}\xb7{1}\u207b\xb9", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +((+$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) / +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']())));
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 2: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}*{1}", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) * +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']());
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 3: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}-{1}", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) - +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']());
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 4: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}+{1}", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) + +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']());
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 5: 
          (this.Paper)['AddArguments']($T04()['Format']("\u221a{0}", this['get_LastValue']()));
          d = (Math.sqrt($S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']())));
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 6: 
          (this.Paper)['AddArguments']($T04()['Format']("1/{0}", this['get_LastValue']()));
          d = +((1 / +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']())));
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 7: 
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) * -1;
          break;

      }
    } catch ($exception) {
      d = 0;
      (this.DisplayBox)['set_Text']("Error");
    }
    return d;
  };

  function MainPage_CalcResults () {
    if (this.LastOper !== $T06().None) {
      this['set_Display']((this['Calc'](this.LastOper)).toString());
      this['UpdateDisplay']();
    }
  };

  function MainPage_CheckResult (d) {
    if (isNaN(d)) {
      throw $S02().Construct("Illegal value");
    }
  };

  function MainPage_DigitBtn_Click (sender, e) {
    var s = (($T0E().$Cast(sender))['get_Content']())['toString']();
    var ids = (JSIL.StringToCharArray(s));
    this['ProcessKey'](ids[0]);
  };

  function MainPage_get_Display () {
    return this._display;
  };

  function MainPage_get_EraseDisplay () {
    return this._erasediplay;
  };

  function MainPage_get_LastValue () {
    if (this._last_val == $T04().Empty) {
      var result = "0";
    } else {
      result = this._last_val;
    }
    return result;
  };

  function MainPage_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      var Style_5fbd9ebaea7344f5a2e878fd47991919 = $S03().Construct();
      Style_5fbd9ebaea7344f5a2e878fd47991919['set_TargetType']($T0E().__Type__);
      var Setter_596f1f37eb6546c88f9f72661433fce7 = $S04().Construct();
      Setter_596f1f37eb6546c88f9f72661433fce7['set_Property']($T12().HeightProperty);
      Setter_596f1f37eb6546c88f9f72661433fce7['set_Value']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "60")));
      var Setter_6198619b449843039b0c15693d821524 = $S04().Construct();
      Setter_6198619b449843039b0c15693d821524['set_Property']($T12().WidthProperty);
      Setter_6198619b449843039b0c15693d821524['set_Value']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "60")));
      var Setter_8b2a33be01ff499a84b67e8d0c3916ac = $S04().Construct();
      Setter_8b2a33be01ff499a84b67e8d0c3916ac['set_Property']($T14().ForegroundProperty);
      Setter_8b2a33be01ff499a84b67e8d0c3916ac['set_Value']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FFBBBBBB")));
      var Setter_9c8cef3a835241569173e271406b1237 = $S04().Construct();
      Setter_9c8cef3a835241569173e271406b1237['set_Property']($T14().FontSizeProperty);
      Setter_9c8cef3a835241569173e271406b1237['set_Value']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "18")));
      (Style_5fbd9ebaea7344f5a2e878fd47991919['get_Setters']())['Add'](Setter_596f1f37eb6546c88f9f72661433fce7);
      (Style_5fbd9ebaea7344f5a2e878fd47991919['get_Setters']())['Add'](Setter_6198619b449843039b0c15693d821524);
      (Style_5fbd9ebaea7344f5a2e878fd47991919['get_Setters']())['Add'](Setter_8b2a33be01ff499a84b67e8d0c3916ac);
      (Style_5fbd9ebaea7344f5a2e878fd47991919['get_Setters']())['Add'](Setter_9c8cef3a835241569173e271406b1237);
      (this['get_Resources']())['Add']("ButtonStyle", Style_5fbd9ebaea7344f5a2e878fd47991919);
      var ScrollViewer_bb5197cbcb084254933efa22e08c4137 = new ($T18())();
      ScrollViewer_bb5197cbcb084254933efa22e08c4137['set_HorizontalScrollBarVisibility']($T19().Auto);
      ScrollViewer_bb5197cbcb084254933efa22e08c4137['set_VerticalScrollBarVisibility']($T19().Auto);
      ScrollViewer_bb5197cbcb084254933efa22e08c4137['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "Black")));
      var Canvas_7974e22b50dc4d57b33fb250c508b367 = new ($T1A())();
      Canvas_7974e22b50dc4d57b33fb250c508b367['set_Height']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "415")));
      Canvas_7974e22b50dc4d57b33fb250c508b367['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "320")));
      Canvas_7974e22b50dc4d57b33fb250c508b367['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF161616")));
      Canvas_7974e22b50dc4d57b33fb250c508b367['set_HorizontalAlignment']($T1C().Center);
      var Border_46a9947dbdbf499c9cdfe6b5b7362977 = new ($T1D())();
      Border_46a9947dbdbf499c9cdfe6b5b7362977['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF222222")));
      $T1A()['SetLeft'](Border_46a9947dbdbf499c9cdfe6b5b7362977, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "0")));
      $T1A()['SetTop'](Border_46a9947dbdbf499c9cdfe6b5b7362977, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "0")));
      Border_46a9947dbdbf499c9cdfe6b5b7362977['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "320")));
      Border_46a9947dbdbf499c9cdfe6b5b7362977['set_Height']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "82")));
      var TextBlock_f7b084f3c70d4bb48cff27595ff0151c = new ($T01())();
      $T1E().prototype['RegisterName'].call(this, "DisplayBox", TextBlock_f7b084f3c70d4bb48cff27595ff0151c);
      TextBlock_f7b084f3c70d4bb48cff27595ff0151c['set_Name']("DisplayBox");
      TextBlock_f7b084f3c70d4bb48cff27595ff0151c['set_Text']("23.5");
      TextBlock_f7b084f3c70d4bb48cff27595ff0151c['set_Foreground']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FFBBBBBB")));
      TextBlock_f7b084f3c70d4bb48cff27595ff0151c['set_FontSize']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "32")));
      TextBlock_f7b084f3c70d4bb48cff27595ff0151c['set_HorizontalAlignment']($T1C().Right);
      (TextBlock_f7b084f3c70d4bb48cff27595ff0151c.Margin = $T1F().$Cast($T13()['ConvertFromInvariantString']($T1F().__Type__, "0,10,10,0"))['MemberwiseClone']());
      Border_46a9947dbdbf499c9cdfe6b5b7362977['set_Child'](TextBlock_f7b084f3c70d4bb48cff27595ff0151c);
      var Button_f0d50ec22b354bf19ae81a74c5a8db81 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BC", Button_f0d50ec22b354bf19ae81a74c5a8db81);
      Button_f0d50ec22b354bf19ae81a74c5a8db81['set_Name']("BC");
      Button_f0d50ec22b354bf19ae81a74c5a8db81['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_f0d50ec22b354bf19ae81a74c5a8db81['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF125166")));
      Button_f0d50ec22b354bf19ae81a74c5a8db81['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "C"));
      $T1A()['SetTop'](Button_f0d50ec22b354bf19ae81a74c5a8db81, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_5fcb1a100f634942813af8030d8c3383 = $S05().Construct();
      StaticResource_5fcb1a100f634942813af8030d8c3383.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_869e6eaf4e384a17a608d628ab4906e2 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BCE", Button_869e6eaf4e384a17a608d628ab4906e2);
      Button_869e6eaf4e384a17a608d628ab4906e2['set_Name']("BCE");
      Button_869e6eaf4e384a17a608d628ab4906e2['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_869e6eaf4e384a17a608d628ab4906e2['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_869e6eaf4e384a17a608d628ab4906e2['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "CE"));
      $T1A()['SetTop'](Button_869e6eaf4e384a17a608d628ab4906e2, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_5879070f6ddd476a8a62e8fac69048a7 = $S05().Construct();
      StaticResource_5879070f6ddd476a8a62e8fac69048a7.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_5fae1c8897ee42ff94335d48dd2a93dc = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B7", Button_5fae1c8897ee42ff94335d48dd2a93dc);
      Button_5fae1c8897ee42ff94335d48dd2a93dc['set_Name']("B7");
      Button_5fae1c8897ee42ff94335d48dd2a93dc['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_5fae1c8897ee42ff94335d48dd2a93dc['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_5fae1c8897ee42ff94335d48dd2a93dc['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "7"));
      $T1A()['SetLeft'](Button_5fae1c8897ee42ff94335d48dd2a93dc, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_5fae1c8897ee42ff94335d48dd2a93dc, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_55030f6bf05647eea159f0104a96d973 = $S05().Construct();
      StaticResource_55030f6bf05647eea159f0104a96d973.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_ba9ec52180ad4f72bb1e8c48bbbfaad2 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B8", Button_ba9ec52180ad4f72bb1e8c48bbbfaad2);
      Button_ba9ec52180ad4f72bb1e8c48bbbfaad2['set_Name']("B8");
      Button_ba9ec52180ad4f72bb1e8c48bbbfaad2['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_ba9ec52180ad4f72bb1e8c48bbbfaad2['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_ba9ec52180ad4f72bb1e8c48bbbfaad2['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "8"));
      $T1A()['SetLeft'](Button_ba9ec52180ad4f72bb1e8c48bbbfaad2, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "130")));
      $T1A()['SetTop'](Button_ba9ec52180ad4f72bb1e8c48bbbfaad2, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_06fcfcd0ff68419f9b923784cf8f2f31 = $S05().Construct();
      StaticResource_06fcfcd0ff68419f9b923784cf8f2f31.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_47c2c37b1ed94d96be6107fffad8bb37 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B9", Button_47c2c37b1ed94d96be6107fffad8bb37);
      Button_47c2c37b1ed94d96be6107fffad8bb37['set_Name']("B9");
      Button_47c2c37b1ed94d96be6107fffad8bb37['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_47c2c37b1ed94d96be6107fffad8bb37['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_47c2c37b1ed94d96be6107fffad8bb37['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "9"));
      $T1A()['SetLeft'](Button_47c2c37b1ed94d96be6107fffad8bb37, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_47c2c37b1ed94d96be6107fffad8bb37, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_73e5746b2ba049a3be83e0a7e7c154e3 = $S05().Construct();
      StaticResource_73e5746b2ba049a3be83e0a7e7c154e3.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_1eec292ca76846cb9d128c1c8c14b433 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B4", Button_1eec292ca76846cb9d128c1c8c14b433);
      Button_1eec292ca76846cb9d128c1c8c14b433['set_Name']("B4");
      Button_1eec292ca76846cb9d128c1c8c14b433['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_1eec292ca76846cb9d128c1c8c14b433['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_1eec292ca76846cb9d128c1c8c14b433['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "4"));
      $T1A()['SetLeft'](Button_1eec292ca76846cb9d128c1c8c14b433, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_1eec292ca76846cb9d128c1c8c14b433, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_f69dfd028281483690b10a88404fc83f = $S05().Construct();
      StaticResource_f69dfd028281483690b10a88404fc83f.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_80f143e06828449c97947305d17aa960 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B5", Button_80f143e06828449c97947305d17aa960);
      Button_80f143e06828449c97947305d17aa960['set_Name']("B5");
      Button_80f143e06828449c97947305d17aa960['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_80f143e06828449c97947305d17aa960['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_80f143e06828449c97947305d17aa960['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "5"));
      $T1A()['SetLeft'](Button_80f143e06828449c97947305d17aa960, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "130")));
      $T1A()['SetTop'](Button_80f143e06828449c97947305d17aa960, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_51ef40f57b9e4c60a87459042bbad8dd = $S05().Construct();
      StaticResource_51ef40f57b9e4c60a87459042bbad8dd.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_503352e8e14a47aeb2d526143931d09f = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B6", Button_503352e8e14a47aeb2d526143931d09f);
      Button_503352e8e14a47aeb2d526143931d09f['set_Name']("B6");
      Button_503352e8e14a47aeb2d526143931d09f['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_503352e8e14a47aeb2d526143931d09f['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_503352e8e14a47aeb2d526143931d09f['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "6"));
      $T1A()['SetLeft'](Button_503352e8e14a47aeb2d526143931d09f, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_503352e8e14a47aeb2d526143931d09f, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_e5da310a94c84f2da2a862586711ebd3 = $S05().Construct();
      StaticResource_e5da310a94c84f2da2a862586711ebd3.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_bd2911677dd245bb9913e296e0d15060 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B1", Button_bd2911677dd245bb9913e296e0d15060);
      Button_bd2911677dd245bb9913e296e0d15060['set_Name']("B1");
      Button_bd2911677dd245bb9913e296e0d15060['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_bd2911677dd245bb9913e296e0d15060['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_bd2911677dd245bb9913e296e0d15060['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "1"));
      $T1A()['SetLeft'](Button_bd2911677dd245bb9913e296e0d15060, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_bd2911677dd245bb9913e296e0d15060, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_4104badafb144517ace3f441af5e41ae = $S05().Construct();
      StaticResource_4104badafb144517ace3f441af5e41ae.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_00d02136d138420385a163ec143bffcb = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B2", Button_00d02136d138420385a163ec143bffcb);
      Button_00d02136d138420385a163ec143bffcb['set_Name']("B2");
      Button_00d02136d138420385a163ec143bffcb['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_00d02136d138420385a163ec143bffcb['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_00d02136d138420385a163ec143bffcb['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "2"));
      $T1A()['SetLeft'](Button_00d02136d138420385a163ec143bffcb, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "130")));
      $T1A()['SetTop'](Button_00d02136d138420385a163ec143bffcb, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_4671fb3aadfa49bdac47003656e0b99c = $S05().Construct();
      StaticResource_4671fb3aadfa49bdac47003656e0b99c.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_b9248687a70349bab7a7ad61e8c74fef = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B3", Button_b9248687a70349bab7a7ad61e8c74fef);
      Button_b9248687a70349bab7a7ad61e8c74fef['set_Name']("B3");
      Button_b9248687a70349bab7a7ad61e8c74fef['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_b9248687a70349bab7a7ad61e8c74fef['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_b9248687a70349bab7a7ad61e8c74fef['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "3"));
      $T1A()['SetLeft'](Button_b9248687a70349bab7a7ad61e8c74fef, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_b9248687a70349bab7a7ad61e8c74fef, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_ea274a3f620c4a24a12f6313cc506394 = $S05().Construct();
      StaticResource_ea274a3f620c4a24a12f6313cc506394.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_e9c7b0a020734d6d80d2191acd8d97e7 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B0", Button_e9c7b0a020734d6d80d2191acd8d97e7);
      Button_e9c7b0a020734d6d80d2191acd8d97e7['set_Name']("B0");
      Button_e9c7b0a020734d6d80d2191acd8d97e7['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_e9c7b0a020734d6d80d2191acd8d97e7['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_e9c7b0a020734d6d80d2191acd8d97e7['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "0"));
      $T1A()['SetLeft'](Button_e9c7b0a020734d6d80d2191acd8d97e7, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_e9c7b0a020734d6d80d2191acd8d97e7, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      Button_e9c7b0a020734d6d80d2191acd8d97e7['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "126")));
      var StaticResource_14f18110f1b5440b90a3ab546f17f319 = $S05().Construct();
      StaticResource_14f18110f1b5440b90a3ab546f17f319.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_d5727503e5664c90b0c5e44f5f99a5e = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BPeriod", Button_d5727503e5664c90b0c5e44f5f99a5e);
      Button_d5727503e5664c90b0c5e44f5f99a5e['set_Name']("BPeriod");
      Button_d5727503e5664c90b0c5e44f5f99a5e['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_d5727503e5664c90b0c5e44f5f99a5e['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      Button_d5727503e5664c90b0c5e44f5f99a5e['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "."));
      $T1A()['SetLeft'](Button_d5727503e5664c90b0c5e44f5f99a5e, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_d5727503e5664c90b0c5e44f5f99a5e, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      var StaticResource_c4ca8d0a045348339d827dd897ab353b = $S05().Construct();
      StaticResource_c4ca8d0a045348339d827dd897ab353b.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_103a6ba654eb44bcaf5429edb7afcd = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BDevide", Button_103a6ba654eb44bcaf5429edb7afcd);
      Button_103a6ba654eb44bcaf5429edb7afcd['set_Name']("BDevide");
      Button_103a6ba654eb44bcaf5429edb7afcd['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_103a6ba654eb44bcaf5429edb7afcd['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_103a6ba654eb44bcaf5429edb7afcd['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "/"));
      $T1A()['SetLeft'](Button_103a6ba654eb44bcaf5429edb7afcd, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_103a6ba654eb44bcaf5429edb7afcd, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_223295ac686147bfa16fe5c04ecac19d = $S05().Construct();
      StaticResource_223295ac686147bfa16fe5c04ecac19d.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_cff37a8eae4a48ba988144614216ae68 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BMultiply", Button_cff37a8eae4a48ba988144614216ae68);
      Button_cff37a8eae4a48ba988144614216ae68['set_Name']("BMultiply");
      Button_cff37a8eae4a48ba988144614216ae68['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_cff37a8eae4a48ba988144614216ae68['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_cff37a8eae4a48ba988144614216ae68['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "*"));
      $T1A()['SetLeft'](Button_cff37a8eae4a48ba988144614216ae68, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_cff37a8eae4a48ba988144614216ae68, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_de64b4818260487c91052764543041bf = $S05().Construct();
      StaticResource_de64b4818260487c91052764543041bf.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_95653b84b79a400eaeeaae1b28bf03c8 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BMinus", Button_95653b84b79a400eaeeaae1b28bf03c8);
      Button_95653b84b79a400eaeeaae1b28bf03c8['set_Name']("BMinus");
      Button_95653b84b79a400eaeeaae1b28bf03c8['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_95653b84b79a400eaeeaae1b28bf03c8['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_95653b84b79a400eaeeaae1b28bf03c8['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "-"));
      $T1A()['SetLeft'](Button_95653b84b79a400eaeeaae1b28bf03c8, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_95653b84b79a400eaeeaae1b28bf03c8, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_f79c447283754c10af62357fbd478951 = $S05().Construct();
      StaticResource_f79c447283754c10af62357fbd478951.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_9414c7674ac7450f9711a26ea942b759 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BPlus", Button_9414c7674ac7450f9711a26ea942b759);
      Button_9414c7674ac7450f9711a26ea942b759['set_Name']("BPlus");
      Button_9414c7674ac7450f9711a26ea942b759['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_9414c7674ac7450f9711a26ea942b759['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_9414c7674ac7450f9711a26ea942b759['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "+"));
      $T1A()['SetLeft'](Button_9414c7674ac7450f9711a26ea942b759, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_9414c7674ac7450f9711a26ea942b759, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      var StaticResource_1a6df8b61d304cf98d1c5040c1e29297 = $S05().Construct();
      StaticResource_1a6df8b61d304cf98d1c5040c1e29297.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_6b57bc201fd74c1b98394d5a14c98bee = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BEqual", Button_6b57bc201fd74c1b98394d5a14c98bee);
      Button_6b57bc201fd74c1b98394d5a14c98bee['set_Name']("BEqual");
      Button_6b57bc201fd74c1b98394d5a14c98bee['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_6b57bc201fd74c1b98394d5a14c98bee['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF125166")));
      Button_6b57bc201fd74c1b98394d5a14c98bee['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "="));
      $T1A()['SetLeft'](Button_6b57bc201fd74c1b98394d5a14c98bee, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_6b57bc201fd74c1b98394d5a14c98bee, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "347")));
      Button_6b57bc201fd74c1b98394d5a14c98bee['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "255")));
      Button_6b57bc201fd74c1b98394d5a14c98bee['set_FontSize']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "30")));
      var StaticResource_63189c6e905e4b15bb6226433613424b = $S05().Construct();
      StaticResource_63189c6e905e4b15bb6226433613424b.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_45f179b9152f4ad3941534d2c1163aa9 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BSqrt", Button_45f179b9152f4ad3941534d2c1163aa9);
      Button_45f179b9152f4ad3941534d2c1163aa9['set_Name']("BSqrt");
      Button_45f179b9152f4ad3941534d2c1163aa9['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_45f179b9152f4ad3941534d2c1163aa9['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "\u221a"));
      Button_45f179b9152f4ad3941534d2c1163aa9['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      $T1A()['SetTop'](Button_45f179b9152f4ad3941534d2c1163aa9, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_08e4eaae6b96448885415549a54b741a = $S05().Construct();
      StaticResource_08e4eaae6b96448885415549a54b741a.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_79c24758ada849519e15fdb5c7d50f65 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BOneOver", Button_79c24758ada849519e15fdb5c7d50f65);
      Button_79c24758ada849519e15fdb5c7d50f65['set_Name']("BOneOver");
      Button_79c24758ada849519e15fdb5c7d50f65['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_79c24758ada849519e15fdb5c7d50f65['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      Button_79c24758ada849519e15fdb5c7d50f65['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "1/x"));
      $T1A()['SetTop'](Button_79c24758ada849519e15fdb5c7d50f65, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      var StaticResource_6e902008921041aaafd8f078700976d7 = $S05().Construct();
      StaticResource_6e902008921041aaafd8f078700976d7.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_b36a7345b3cf40f2aefee4f02906b78b = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BPM", Button_b36a7345b3cf40f2aefee4f02906b78b);
      Button_b36a7345b3cf40f2aefee4f02906b78b['set_Name']("BPM");
      Button_b36a7345b3cf40f2aefee4f02906b78b['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_b36a7345b3cf40f2aefee4f02906b78b['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      Button_b36a7345b3cf40f2aefee4f02906b78b['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "+/-"));
      $T1A()['SetTop'](Button_b36a7345b3cf40f2aefee4f02906b78b, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "347")));
      var StaticResource_8b2722ec53c04fc6bd4b409b264ce4cb = $S05().Construct();
      StaticResource_8b2722ec53c04fc6bd4b409b264ce4cb.StaticResource$ResourceKey$value = "ButtonStyle";
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Border_46a9947dbdbf499c9cdfe6b5b7362977);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_f0d50ec22b354bf19ae81a74c5a8db81);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_869e6eaf4e384a17a608d628ab4906e2);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_5fae1c8897ee42ff94335d48dd2a93dc);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_ba9ec52180ad4f72bb1e8c48bbbfaad2);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_47c2c37b1ed94d96be6107fffad8bb37);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_1eec292ca76846cb9d128c1c8c14b433);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_80f143e06828449c97947305d17aa960);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_503352e8e14a47aeb2d526143931d09f);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_bd2911677dd245bb9913e296e0d15060);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_00d02136d138420385a163ec143bffcb);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_b9248687a70349bab7a7ad61e8c74fef);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_e9c7b0a020734d6d80d2191acd8d97e7);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_d5727503e5664c90b0c5e44f5f99a5e);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_103a6ba654eb44bcaf5429edb7afcd);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_cff37a8eae4a48ba988144614216ae68);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_95653b84b79a400eaeeaae1b28bf03c8);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_9414c7674ac7450f9711a26ea942b759);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_6b57bc201fd74c1b98394d5a14c98bee);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_45f179b9152f4ad3941534d2c1163aa9);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_79c24758ada849519e15fdb5c7d50f65);
      (Canvas_7974e22b50dc4d57b33fb250c508b367['get_Children']())['Add'](Button_b36a7345b3cf40f2aefee4f02906b78b);
      ScrollViewer_bb5197cbcb084254933efa22e08c4137['set_Content'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      this['set_Content'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      this.DisplayBox = TextBlock_f7b084f3c70d4bb48cff27595ff0151c;
      this.BC = Button_f0d50ec22b354bf19ae81a74c5a8db81;
      this.BCE = Button_869e6eaf4e384a17a608d628ab4906e2;
      this.B7 = Button_5fae1c8897ee42ff94335d48dd2a93dc;
      this.B8 = Button_ba9ec52180ad4f72bb1e8c48bbbfaad2;
      this.B9 = Button_47c2c37b1ed94d96be6107fffad8bb37;
      this.B4 = Button_1eec292ca76846cb9d128c1c8c14b433;
      this.B5 = Button_80f143e06828449c97947305d17aa960;
      this.B6 = Button_503352e8e14a47aeb2d526143931d09f;
      this.B1 = Button_bd2911677dd245bb9913e296e0d15060;
      this.B2 = Button_00d02136d138420385a163ec143bffcb;
      this.B3 = Button_b9248687a70349bab7a7ad61e8c74fef;
      this.B0 = Button_e9c7b0a020734d6d80d2191acd8d97e7;
      this.BPeriod = Button_d5727503e5664c90b0c5e44f5f99a5e;
      this.BDevide = Button_103a6ba654eb44bcaf5429edb7afcd;
      this.BMultiply = Button_cff37a8eae4a48ba988144614216ae68;
      this.BMinus = Button_95653b84b79a400eaeeaae1b28bf03c8;
      this.BPlus = Button_9414c7674ac7450f9711a26ea942b759;
      this.BEqual = Button_6b57bc201fd74c1b98394d5a14c98bee;
      this.BSqrt = Button_45f179b9152f4ad3941534d2c1163aa9;
      this.BOneOver = Button_79c24758ada849519e15fdb5c7d50f65;
      this.BPM = Button_b36a7345b3cf40f2aefee4f02906b78b;
      var parents_2420112282494d60a2c741216072deef = $S06().Construct();
      parents_2420112282494d60a2c741216072deef['Add'](Button_f0d50ec22b354bf19ae81a74c5a8db81);
      parents_2420112282494d60a2c741216072deef['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_2420112282494d60a2c741216072deef['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_2420112282494d60a2c741216072deef['Add'](this);
      Button_f0d50ec22b354bf19ae81a74c5a8db81['set_Style']($T10().$Cast(StaticResource_5fcb1a100f634942813af8030d8c3383['ProvideValue'](new ($T26())(Button_f0d50ec22b354bf19ae81a74c5a8db81, null, parents_2420112282494d60a2c741216072deef))));
      var parents_54721b1fc205499aa52fe51e86122649 = $S06().Construct();
      parents_54721b1fc205499aa52fe51e86122649['Add'](Button_869e6eaf4e384a17a608d628ab4906e2);
      parents_54721b1fc205499aa52fe51e86122649['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_54721b1fc205499aa52fe51e86122649['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_54721b1fc205499aa52fe51e86122649['Add'](this);
      Button_869e6eaf4e384a17a608d628ab4906e2['set_Style']($T10().$Cast(StaticResource_5879070f6ddd476a8a62e8fac69048a7['ProvideValue'](new ($T26())(Button_869e6eaf4e384a17a608d628ab4906e2, null, parents_54721b1fc205499aa52fe51e86122649))));
      var parents_e803850d244e4973a87f5ab083a3d284 = $S06().Construct();
      parents_e803850d244e4973a87f5ab083a3d284['Add'](Button_5fae1c8897ee42ff94335d48dd2a93dc);
      parents_e803850d244e4973a87f5ab083a3d284['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_e803850d244e4973a87f5ab083a3d284['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_e803850d244e4973a87f5ab083a3d284['Add'](this);
      Button_5fae1c8897ee42ff94335d48dd2a93dc['set_Style']($T10().$Cast(StaticResource_55030f6bf05647eea159f0104a96d973['ProvideValue'](new ($T26())(Button_5fae1c8897ee42ff94335d48dd2a93dc, null, parents_e803850d244e4973a87f5ab083a3d284))));
      var parents_7c7980bc8dbb4cf89cc666bb5c98337b = $S06().Construct();
      parents_7c7980bc8dbb4cf89cc666bb5c98337b['Add'](Button_ba9ec52180ad4f72bb1e8c48bbbfaad2);
      parents_7c7980bc8dbb4cf89cc666bb5c98337b['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_7c7980bc8dbb4cf89cc666bb5c98337b['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_7c7980bc8dbb4cf89cc666bb5c98337b['Add'](this);
      Button_ba9ec52180ad4f72bb1e8c48bbbfaad2['set_Style']($T10().$Cast(StaticResource_06fcfcd0ff68419f9b923784cf8f2f31['ProvideValue'](new ($T26())(Button_ba9ec52180ad4f72bb1e8c48bbbfaad2, null, parents_7c7980bc8dbb4cf89cc666bb5c98337b))));
      var parents_b3b61474835f4ebca93a72afcce8a301 = $S06().Construct();
      parents_b3b61474835f4ebca93a72afcce8a301['Add'](Button_47c2c37b1ed94d96be6107fffad8bb37);
      parents_b3b61474835f4ebca93a72afcce8a301['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_b3b61474835f4ebca93a72afcce8a301['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_b3b61474835f4ebca93a72afcce8a301['Add'](this);
      Button_47c2c37b1ed94d96be6107fffad8bb37['set_Style']($T10().$Cast(StaticResource_73e5746b2ba049a3be83e0a7e7c154e3['ProvideValue'](new ($T26())(Button_47c2c37b1ed94d96be6107fffad8bb37, null, parents_b3b61474835f4ebca93a72afcce8a301))));
      var parents_0720bec70f9c407aa5d0cef126df194c = $S06().Construct();
      parents_0720bec70f9c407aa5d0cef126df194c['Add'](Button_1eec292ca76846cb9d128c1c8c14b433);
      parents_0720bec70f9c407aa5d0cef126df194c['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_0720bec70f9c407aa5d0cef126df194c['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_0720bec70f9c407aa5d0cef126df194c['Add'](this);
      Button_1eec292ca76846cb9d128c1c8c14b433['set_Style']($T10().$Cast(StaticResource_f69dfd028281483690b10a88404fc83f['ProvideValue'](new ($T26())(Button_1eec292ca76846cb9d128c1c8c14b433, null, parents_0720bec70f9c407aa5d0cef126df194c))));
      var parents_fb6746c51bbd43a2b587ac4e211190 = $S06().Construct();
      parents_fb6746c51bbd43a2b587ac4e211190['Add'](Button_80f143e06828449c97947305d17aa960);
      parents_fb6746c51bbd43a2b587ac4e211190['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_fb6746c51bbd43a2b587ac4e211190['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_fb6746c51bbd43a2b587ac4e211190['Add'](this);
      Button_80f143e06828449c97947305d17aa960['set_Style']($T10().$Cast(StaticResource_51ef40f57b9e4c60a87459042bbad8dd['ProvideValue'](new ($T26())(Button_80f143e06828449c97947305d17aa960, null, parents_fb6746c51bbd43a2b587ac4e211190))));
      var parents_6aaf113b4a094a59a7da4aa132ae886c = $S06().Construct();
      parents_6aaf113b4a094a59a7da4aa132ae886c['Add'](Button_503352e8e14a47aeb2d526143931d09f);
      parents_6aaf113b4a094a59a7da4aa132ae886c['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_6aaf113b4a094a59a7da4aa132ae886c['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_6aaf113b4a094a59a7da4aa132ae886c['Add'](this);
      Button_503352e8e14a47aeb2d526143931d09f['set_Style']($T10().$Cast(StaticResource_e5da310a94c84f2da2a862586711ebd3['ProvideValue'](new ($T26())(Button_503352e8e14a47aeb2d526143931d09f, null, parents_6aaf113b4a094a59a7da4aa132ae886c))));
      var parents_d84ac308117a46e597e2351ae0919e1d = $S06().Construct();
      parents_d84ac308117a46e597e2351ae0919e1d['Add'](Button_bd2911677dd245bb9913e296e0d15060);
      parents_d84ac308117a46e597e2351ae0919e1d['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_d84ac308117a46e597e2351ae0919e1d['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_d84ac308117a46e597e2351ae0919e1d['Add'](this);
      Button_bd2911677dd245bb9913e296e0d15060['set_Style']($T10().$Cast(StaticResource_4104badafb144517ace3f441af5e41ae['ProvideValue'](new ($T26())(Button_bd2911677dd245bb9913e296e0d15060, null, parents_d84ac308117a46e597e2351ae0919e1d))));
      var parents_0619191e604c434e9a1709da3e3e3b8d = $S06().Construct();
      parents_0619191e604c434e9a1709da3e3e3b8d['Add'](Button_00d02136d138420385a163ec143bffcb);
      parents_0619191e604c434e9a1709da3e3e3b8d['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_0619191e604c434e9a1709da3e3e3b8d['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_0619191e604c434e9a1709da3e3e3b8d['Add'](this);
      Button_00d02136d138420385a163ec143bffcb['set_Style']($T10().$Cast(StaticResource_4671fb3aadfa49bdac47003656e0b99c['ProvideValue'](new ($T26())(Button_00d02136d138420385a163ec143bffcb, null, parents_0619191e604c434e9a1709da3e3e3b8d))));
      var parents_ea6d1b41b8764b759517f5e20aaad276 = $S06().Construct();
      parents_ea6d1b41b8764b759517f5e20aaad276['Add'](Button_b9248687a70349bab7a7ad61e8c74fef);
      parents_ea6d1b41b8764b759517f5e20aaad276['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_ea6d1b41b8764b759517f5e20aaad276['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_ea6d1b41b8764b759517f5e20aaad276['Add'](this);
      Button_b9248687a70349bab7a7ad61e8c74fef['set_Style']($T10().$Cast(StaticResource_ea274a3f620c4a24a12f6313cc506394['ProvideValue'](new ($T26())(Button_b9248687a70349bab7a7ad61e8c74fef, null, parents_ea6d1b41b8764b759517f5e20aaad276))));
      var parents_fa012b68f600490481aab335a41ce149 = $S06().Construct();
      parents_fa012b68f600490481aab335a41ce149['Add'](Button_e9c7b0a020734d6d80d2191acd8d97e7);
      parents_fa012b68f600490481aab335a41ce149['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_fa012b68f600490481aab335a41ce149['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_fa012b68f600490481aab335a41ce149['Add'](this);
      Button_e9c7b0a020734d6d80d2191acd8d97e7['set_Style']($T10().$Cast(StaticResource_14f18110f1b5440b90a3ab546f17f319['ProvideValue'](new ($T26())(Button_e9c7b0a020734d6d80d2191acd8d97e7, null, parents_fa012b68f600490481aab335a41ce149))));
      var parents_f66ed122613e49aa82156ccaa00fe49e = $S06().Construct();
      parents_f66ed122613e49aa82156ccaa00fe49e['Add'](Button_d5727503e5664c90b0c5e44f5f99a5e);
      parents_f66ed122613e49aa82156ccaa00fe49e['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_f66ed122613e49aa82156ccaa00fe49e['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_f66ed122613e49aa82156ccaa00fe49e['Add'](this);
      Button_d5727503e5664c90b0c5e44f5f99a5e['set_Style']($T10().$Cast(StaticResource_c4ca8d0a045348339d827dd897ab353b['ProvideValue'](new ($T26())(Button_d5727503e5664c90b0c5e44f5f99a5e, null, parents_f66ed122613e49aa82156ccaa00fe49e))));
      var parents_5222e47dfee34e63b2339621c021dbc5 = $S06().Construct();
      parents_5222e47dfee34e63b2339621c021dbc5['Add'](Button_103a6ba654eb44bcaf5429edb7afcd);
      parents_5222e47dfee34e63b2339621c021dbc5['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_5222e47dfee34e63b2339621c021dbc5['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_5222e47dfee34e63b2339621c021dbc5['Add'](this);
      Button_103a6ba654eb44bcaf5429edb7afcd['set_Style']($T10().$Cast(StaticResource_223295ac686147bfa16fe5c04ecac19d['ProvideValue'](new ($T26())(Button_103a6ba654eb44bcaf5429edb7afcd, null, parents_5222e47dfee34e63b2339621c021dbc5))));
      var parents_5ba719fad0e14cd3960aa0d8fa77de7d = $S06().Construct();
      parents_5ba719fad0e14cd3960aa0d8fa77de7d['Add'](Button_cff37a8eae4a48ba988144614216ae68);
      parents_5ba719fad0e14cd3960aa0d8fa77de7d['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_5ba719fad0e14cd3960aa0d8fa77de7d['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_5ba719fad0e14cd3960aa0d8fa77de7d['Add'](this);
      Button_cff37a8eae4a48ba988144614216ae68['set_Style']($T10().$Cast(StaticResource_de64b4818260487c91052764543041bf['ProvideValue'](new ($T26())(Button_cff37a8eae4a48ba988144614216ae68, null, parents_5ba719fad0e14cd3960aa0d8fa77de7d))));
      var parents_7f02a98d4c9549a7aee684eb754a707c = $S06().Construct();
      parents_7f02a98d4c9549a7aee684eb754a707c['Add'](Button_95653b84b79a400eaeeaae1b28bf03c8);
      parents_7f02a98d4c9549a7aee684eb754a707c['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_7f02a98d4c9549a7aee684eb754a707c['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_7f02a98d4c9549a7aee684eb754a707c['Add'](this);
      Button_95653b84b79a400eaeeaae1b28bf03c8['set_Style']($T10().$Cast(StaticResource_f79c447283754c10af62357fbd478951['ProvideValue'](new ($T26())(Button_95653b84b79a400eaeeaae1b28bf03c8, null, parents_7f02a98d4c9549a7aee684eb754a707c))));
      var parents_49af95ce329446ee956185b422b9a83f = $S06().Construct();
      parents_49af95ce329446ee956185b422b9a83f['Add'](Button_9414c7674ac7450f9711a26ea942b759);
      parents_49af95ce329446ee956185b422b9a83f['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_49af95ce329446ee956185b422b9a83f['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_49af95ce329446ee956185b422b9a83f['Add'](this);
      Button_9414c7674ac7450f9711a26ea942b759['set_Style']($T10().$Cast(StaticResource_1a6df8b61d304cf98d1c5040c1e29297['ProvideValue'](new ($T26())(Button_9414c7674ac7450f9711a26ea942b759, null, parents_49af95ce329446ee956185b422b9a83f))));
      var parents_5edaa53aafda4361b1f739df5358d2dd = $S06().Construct();
      parents_5edaa53aafda4361b1f739df5358d2dd['Add'](Button_6b57bc201fd74c1b98394d5a14c98bee);
      parents_5edaa53aafda4361b1f739df5358d2dd['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_5edaa53aafda4361b1f739df5358d2dd['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_5edaa53aafda4361b1f739df5358d2dd['Add'](this);
      Button_6b57bc201fd74c1b98394d5a14c98bee['set_Style']($T10().$Cast(StaticResource_63189c6e905e4b15bb6226433613424b['ProvideValue'](new ($T26())(Button_6b57bc201fd74c1b98394d5a14c98bee, null, parents_5edaa53aafda4361b1f739df5358d2dd))));
      var parents_eab5c21da13f48699085f2c5782706 = $S06().Construct();
      parents_eab5c21da13f48699085f2c5782706['Add'](Button_45f179b9152f4ad3941534d2c1163aa9);
      parents_eab5c21da13f48699085f2c5782706['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_eab5c21da13f48699085f2c5782706['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_eab5c21da13f48699085f2c5782706['Add'](this);
      Button_45f179b9152f4ad3941534d2c1163aa9['set_Style']($T10().$Cast(StaticResource_08e4eaae6b96448885415549a54b741a['ProvideValue'](new ($T26())(Button_45f179b9152f4ad3941534d2c1163aa9, null, parents_eab5c21da13f48699085f2c5782706))));
      var parents_8a0ed55318064a0686f716d1acd80e6a = $S06().Construct();
      parents_8a0ed55318064a0686f716d1acd80e6a['Add'](Button_79c24758ada849519e15fdb5c7d50f65);
      parents_8a0ed55318064a0686f716d1acd80e6a['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_8a0ed55318064a0686f716d1acd80e6a['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_8a0ed55318064a0686f716d1acd80e6a['Add'](this);
      Button_79c24758ada849519e15fdb5c7d50f65['set_Style']($T10().$Cast(StaticResource_6e902008921041aaafd8f078700976d7['ProvideValue'](new ($T26())(Button_79c24758ada849519e15fdb5c7d50f65, null, parents_8a0ed55318064a0686f716d1acd80e6a))));
      var parents_97efbf452c1c4f85bb0462248019c336 = $S06().Construct();
      parents_97efbf452c1c4f85bb0462248019c336['Add'](Button_b36a7345b3cf40f2aefee4f02906b78b);
      parents_97efbf452c1c4f85bb0462248019c336['Add'](Canvas_7974e22b50dc4d57b33fb250c508b367);
      parents_97efbf452c1c4f85bb0462248019c336['Add'](ScrollViewer_bb5197cbcb084254933efa22e08c4137);
      parents_97efbf452c1c4f85bb0462248019c336['Add'](this);
      Button_b36a7345b3cf40f2aefee4f02906b78b['set_Style']($T10().$Cast(StaticResource_8b2722ec53c04fc6bd4b409b264ce4cb['ProvideValue'](new ($T26())(Button_b36a7345b3cf40f2aefee4f02906b78b, null, parents_97efbf452c1c4f85bb0462248019c336))));
    }
  };

  function MainPage_OperBtn_Click (sender, e) {
    this['ProcessOperation']((($T0E().$Cast(sender))['get_Name']())['toString']());
  };

  function MainPage_ProcessKey (c) {
    if (this['get_EraseDisplay']()) {
      this['set_Display']($T04().Empty);
      this['set_EraseDisplay'](false);
    }
    this['AddToDisplay'](c);
  };

  function MainPage_ProcessOperation (s) {
    if (s !== null) {
      switch (s) {
        case "BPM": 
          this.LastOper = $T06().Negate;
          this['set_LastValue'](this['get_Display']());
          this['CalcResults']();
          this['set_LastValue'](this['get_Display']());
          this['set_EraseDisplay'](true);
          this.LastOper = $T06().None;
          break;

        case "BDevide": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Devide;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Devide;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BMultiply": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Multiply;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Multiply;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BMinus": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Subtract;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Subtract;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BPlus": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Add;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Add;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BEqual": 
          if (!this['get_EraseDisplay']()) {
            this['CalcResults']();
            this['set_EraseDisplay'](true);
            this.LastOper = $T06().None;
            this['set_LastValue'](this['get_Display']());
          }
          break;

        case "BSqrt": 
          this.LastOper = $T06().Sqrt;
          this['set_LastValue'](this['get_Display']());
          this['CalcResults']();
          this['set_LastValue'](this['get_Display']());
          this['set_EraseDisplay'](true);
          this.LastOper = $T06().None;
          break;

        case "BOneOver": 
          this.LastOper = $T06().OneX;
          this['set_LastValue'](this['get_Display']());
          this['CalcResults']();
          this['set_LastValue'](this['get_Display']());
          this['set_EraseDisplay'](true);
          this.LastOper = $T06().None;
          break;

        case "BC": 
          this.LastOper = $T06().None;
          this['set_Display'](this.LastValue = $T04().Empty);
          (this.Paper)['Clear']();
          this['UpdateDisplay']();
          break;

        case "BCE": 
          this.LastOper = $T06().None;
          this['set_Display'](this['get_LastValue']());
          this['UpdateDisplay']();
          break;

      }
    }
  };

  function MainPage_set_Display (value) {
    this._display = value;
  };

  function MainPage_set_EraseDisplay (value) {
    this._erasediplay = value;
  };

  function MainPage_set_LastValue (value) {
    this._last_val = value;
  };

  function MainPage_UpdateDisplay () {
    if ($T04()['IsNullOrEmpty'](this['get_Display']())) {
      (this.DisplayBox)['set_Text']("0");
    } else {
      (this.DisplayBox)['set_Text'](this['get_Display']());
    }
  };

  JSIL.MakeType({
      BaseType: $asm00.TypeRef("Windows.UI.Xaml.Controls.Page"), 
      Name: "SampleCalculatorApp1.MainPage", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MainPage__ctor
    );

    $.Method({Static:false, Public:false}, "AddToDisplay", 
      JSIL.MethodSignature.Action($.Char), 
      MainPage_AddToDisplay
    );

    $.Method({Static:false, Public:false}, "Calc", 
      new JSIL.MethodSignature($.Double, [$asm07.TypeRef("SampleCalculatorApp1.MainPage+Operation")]), 
      MainPage_Calc
    );

    $.Method({Static:false, Public:false}, "CalcResults", 
      JSIL.MethodSignature.Void, 
      MainPage_CalcResults
    );

    $.Method({Static:false, Public:false}, "CheckResult", 
      JSIL.MethodSignature.Action($.Double), 
      MainPage_CheckResult
    );

    $.Method({Static:false, Public:false}, "DigitBtn_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm00.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_DigitBtn_Click
    );

    $.Method({Static:false, Public:false}, "get_Display", 
      JSIL.MethodSignature.Return($.String), 
      MainPage_get_Display
    );

    $.Method({Static:false, Public:false}, "get_EraseDisplay", 
      JSIL.MethodSignature.Return($.Boolean), 
      MainPage_get_EraseDisplay
    );

    $.Method({Static:false, Public:false}, "get_LastValue", 
      JSIL.MethodSignature.Return($.String), 
      MainPage_get_LastValue
    );

    $.Method({Static:false, Public:false}, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      MainPage_InitializeComponent
    );

    $.Method({Static:false, Public:false}, "OperBtn_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm00.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_OperBtn_Click
    );

    $.Method({Static:false, Public:false}, "ProcessKey", 
      JSIL.MethodSignature.Action($.Char), 
      MainPage_ProcessKey
    );

    $.Method({Static:false, Public:false}, "ProcessOperation", 
      JSIL.MethodSignature.Action($.String), 
      MainPage_ProcessOperation
    );

    $.Method({Static:false, Public:false}, "set_Display", 
      JSIL.MethodSignature.Action($.String), 
      MainPage_set_Display
    );

    $.Method({Static:false, Public:false}, "set_EraseDisplay", 
      JSIL.MethodSignature.Action($.Boolean), 
      MainPage_set_EraseDisplay
    );

    $.Method({Static:false, Public:false}, "set_LastValue", 
      JSIL.MethodSignature.Action($.String), 
      MainPage_set_LastValue
    );

    $.Method({Static:false, Public:false}, "UpdateDisplay", 
      JSIL.MethodSignature.Void, 
      MainPage_UpdateDisplay
    );

    $['Field']({Static:false, Public:false}, "PaperBox", $asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")); 
    $['Field']({Static:false, Public:false}, "Paper", $asm07.TypeRef("SampleCalculatorApp1.PaperTrail")); 
    $['Field']({Static:false, Public:false}, "LastOper", $asm07.TypeRef("SampleCalculatorApp1.MainPage+Operation")); 
    $['Field']({Static:false, Public:false}, "_display", $.String); 
    $['Field']({Static:false, Public:false}, "_last_val", $.String); 
    $['Field']({Static:false, Public:false}, "_erasediplay", $.Boolean); 
    $['Field']({Static:false, Public:false}, "DisplayBox", $asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")); 
    $['Field']({Static:false, Public:false}, "BC", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BCE", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B7", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B8", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B9", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B4", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B5", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B6", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B1", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B2", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B3", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B0", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BPeriod", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BDevide", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BMultiply", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BMinus", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BPlus", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BEqual", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BSqrt", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BOneOver", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BPM", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    $.Property({Static:false, Public:false}, "EraseDisplay", $.Boolean);

    $.Property({Static:false, Public:false}, "LastValue", $.String);

    $.Property({Static:false, Public:false}, "Display", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* enum SampleCalculatorApp1.MainPage+Operation */ 

JSIL.MakeEnum(
  {
    FullName: "SampleCalculatorApp1.MainPage+Operation", 
    BaseType: $asm06.TypeRef("System.Int32"), 
    IsPublic: false, 
    IsFlags: false, 
  }, 
  {
    None: 0, 
    Devide: 1, 
    Multiply: 2, 
    Subtract: 3, 
    Add: 4, 
    Sqrt: 5, 
    OneX: 6, 
    Negate: 7, 
  }
);

JSIL.DeclareNamespace("PreviewOnWinRT");
/* class PreviewOnWinRT.Operation */ 

(function Operation$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm06.System.String)) ();
  };

  function Operation__ctor (name) {
    this['set_Name'](name);
  };

  function Operation_get_Name () {
    return this._name;
  };

  function Operation_set_Name (value) {
    this._name = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "PreviewOnWinRT.Operation", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      Operation__ctor
    );

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      Operation_get_Name
    );

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      Operation_set_Name
    );

    $['Field']({Static:false, Public:false}, "_name", $.String); 
    $.Property({Static:false, Public:true }, "Name", $.String);

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class PreviewOnWinRT.Operations */ 

(function Operations$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm07.PreviewOnWinRT.Operation)) ();
  };

  function Operations__ctor () {
  };

  function Operations_BPlus () {
    return $thisType._BPlus;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "PreviewOnWinRT.Operations", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      Operations__ctor
    );

    $.Method({Static:true , Public:true }, "BPlus", 
      JSIL.MethodSignature.Return($asm07.TypeRef("PreviewOnWinRT.Operation")), 
      Operations_BPlus
    );

    $['Field']({Static:true , Public:false}, "_BPlus", $asm07.TypeRef("PreviewOnWinRT.Operation")); 
    function Operations__cctor () {
      $thisType._BPlus = new ($T00())("BPlus");
    };


    $.Method({Static:true , Public:false}, ".cctor", 
      JSIL.MethodSignature.Void, 
      Operations__cctor
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SampleCalculatorApp1.PaperTrail */ 

(function PaperTrail$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.TextBlock)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.String)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm06.System.Environment)) ();
  };

  function PaperTrail__ctor$00 () {
  };

  function PaperTrail__ctor$01 (paperBox) {
    this.PaperBox = paperBox;
  };

  function PaperTrail_AddArguments (a) {
    this.args = a;
  };

  function PaperTrail_AddResult (r) {
    var expr_07 = this.PaperBox;
    expr_07['set_Text'](JSIL.ConcatString(expr_07['get_Text'](), $T01()['Format']("{0}={1}{2}", this.args, r, $T02()['get_NewLine']())));
  };

  function PaperTrail_Clear () {
    (this.PaperBox)['set_Text'](this.args = $T01().Empty);
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "SampleCalculatorApp1.PaperTrail", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      PaperTrail__ctor$00
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")), 
      PaperTrail__ctor$01
    );

    $.Method({Static:false, Public:true }, "AddArguments", 
      JSIL.MethodSignature.Action($.String), 
      PaperTrail_AddArguments
    );

    $.Method({Static:false, Public:true }, "AddResult", 
      JSIL.MethodSignature.Action($.String), 
      PaperTrail_AddResult
    );

    $.Method({Static:false, Public:true }, "Clear", 
      JSIL.MethodSignature.Void, 
      PaperTrail_Clear
    );

    $['Field']({Static:false, Public:false}, "args", $.String); 
    $['Field']({Static:false, Public:false}, "PaperBox", $asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

